create table requisitos(
APP_ID int,
MINIMO_NECESSARIO text,
REQUISITOS_MAC text,
REQUISITOS_LINUX text,
REQUISITOS_WINDOWS text
);

select * from requisitos;

START TRANSACTION;
COMMIT;
SET AUTOCOMMIT = 0;

ALTER TABLE `REQUISITOS` ADD foreign key (APP_ID) REFERENCES `STEAM_DADOS`(APP_ID);
